version: '3'

services:
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #mock_metrics:
  #  build: .
  #  ports:
  #    - "8000:8000"
