name: Build and Test Server API URLs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #    - uses: actions/checkout@main
    - name: install python packages
      run: pip install flask gunicorn

      #- uses: actions/checkout@main
    - name: Install php and curl
      run:  apt install php php-cli curl

      #- uses: actions/checkout@main
    - name: Start python and php server
      run:  python3 kickstart.py

      #- uses: actions/checkout@main
    - name: Check API url locations
      run: |
          curl -X GET http://localhost:5000/api/pump/status


